export enum ExpectedContractTypeEnum {
  'ONLY EMPLOYMENT CONTRACT' = 'ONLY EMPLOYMENT CONTRACT',
  'POSSIBLE B2B' = 'POSSIBLE B2B',
  'POSSIBLE MANDATE CONTRACT/CONTRACT WORK' = 'POSSIBLE MANDATE CONTRACT/CONTRACT WORK',
  'NO PREFERENCES' = 'NO PREFERENCES',
}
