export enum ExpectedTypeWorkEnum {
  'AT LOCATION' = 'AT LOCATION',
  'WILLINGNESS TO RELOCATE' = 'WILLINGNESS TO RELOCATE',
  'ONLY REMOTELY' = 'ONLY REMOTELY',
  'HYBRID' = 'HYBRID',
  'IRRELEVANT' = 'IRRELEVANT',
}
